apiVersion: v1
kind: Service
metadata:
  namespace: pa-api
  name: pa-api
  labels:
    run: pa-api
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: api
    - port: 3005
      targetPort: 3005
      protocol: TCP
      name: contacts
  selector:
    app: pa-api